CD-194: Linux Updates Count
domotz/custom-driver pull request #142
Opened 2023-09-25 09:03 UTC by mariemm97

2023-09-27 07:19 UTC, kgskgs requested changes

2023-09-27 07:19 UTC, kgskgs commented on examples/ssh/linux_updates_count.js
> +    for (var j = 0; j < packageFilters.length; j++) {
while we don't support optional parameters yet, if we do at a some point, this could become one, and then we'd fetch the whole list if it's missing

2023-09-27 07:19 UTC, kgskgs commented on examples/ssh/linux_updates_count.json
> +    "name": "Linux Updates Count",
Since the script is using apt, it will only work for debian based distributions. The wording here and below should most likely be adjusted.

2023-09-27 07:19 UTC, kgskgs commented on examples/ssh/linux_updates_count.json
> +            "label": "Count Updates"
not sure this is appropriate, looking at the script this list should contain the names of the packages that are to be checked for updates

2023-09-27 07:19 UTC, kgskgs commented on examples/ssh/linux_updates_count.json
> +    "sample_period": 3600,
change to `sample_period_s`

2023-10-06 12:39 UTC, GeorgiTsatsev approved these changes

2023-10-06 12:39 UTC, merged