CD-240: Clearone Script
domotz/custom-driver pull request #180
Opened 2023-11-16 10:12 UTC by mariemm97

2023-11-22 15:14 UTC, mohamedkallel requested changes

2023-11-22 15:14 UTC, mohamedkallel commented on examples/http/clearone_convergence.js
> +function getData() {
for a clearer code extract split this function to 2 separate promises, the first for 
httpGet("/dashboard-back/api/devices/pro-audio/search?q=" + D.device.ip())
if this is successfull call the next 
httpGet("/dashboard-back/api/devices/pro-audio/" + data.avDevices[0].id)

if we name the first one search() and the second one getDetail() the get status will be like this

search().
    then(getDetail).
    then(extractVariables)...

2023-11-28 13:35 UTC, GeorgiTsatsev commented on examples/http/clearone_convergence.js
> +		protocol: "http:",
The default protocol is http, this should not be needed

2023-11-28 13:35 UTC, GeorgiTsatsev commented on examples/http/clearone_convergence.js
> +		protocol: "http:",
Formatting appears wrong

2023-11-28 13:35 UTC, GeorgiTsatsev commented on examples/http/clearone_convergence.js
> +        if (response.statusCode === 401 || response.statusCode === 403) {
status code checks should be else ifs

2023-11-28 13:36 UTC, GeorgiTsatsev commented on examples/http/clearone_convergence.js
> +            deviceInfo = data.avDevices[0];
what if the avDevices is not part of the data response? (eg an error or no avDevices in the response body at all)

2023-11-28 13:37 UTC, GeorgiTsatsev commented on examples/http/clearone_convergence.js
> +    var variables = [
maybe add typing

2023-11-28 14:06 UTC, GeorgiTsatsev commented on examples/http/clearone_convergence.js
> +        .then(D.success)
the search does not check for any errors in the response data

2023-12-21 11:26 UTC, GeorgiTsatsev approved these changes

2023-12-21 12:00 UTC, GeorgiTsatsev approved these changes

2023-12-21 12:06 UTC, mohamedkallel approved these changes

2023-12-21 12:10 UTC, GeorgiTsatsev approved these changes

2023-12-21 12:10 UTC, merged