CD-314: Sonicwall firewall - Security services status and license
domotz/custom-driver pull request #210
Opened 2024-01-24 16:31 UTC by mariemm97

2024-02-01 09:40 UTC, mohamedkallel requested changes

2024-02-01 09:40 UTC, mohamedkallel commented on examples/http/sonicwall_security_services_status_license.js
> +function login() {
the service is public no login needed

2024-02-01 11:32 UTC, mohamedkallel approved these changes

2024-02-05 17:15 UTC, mohamedkallel approved these changes

2024-02-09 10:56 UTC, GeorgiTsatsev approved these changes

2024-02-09 10:56 UTC, merged