CD-319: Fujitsu - iRMC - Fans - REST API
domotz/custom-driver pull request #216
Opened 2024-01-29 15:47 UTC by mariemm97

2024-01-30 13:22 UTC, mohamedkallel requested changes

2024-01-30 13:22 UTC, mohamedkallel commented on examples/http/fujitsu_irmc_fans_rest_api.js
> +    for (var i = 0; i < data.Fans.length; i++) {
get the unti from the first record instead of making a loop if the data.Fans has more than one element

2024-01-31 09:16 UTC, mohamedkallel requested changes

2024-01-31 09:16 UTC, mohamedkallel commented on examples/http/fujitsu_irmc_fans_rest_api.js
> +    if (!data.Fans || data.Fans.length === 0) {
if there is no data the process will not exit and it will continue and this will cause an error in line 60, you should fail if there is no data

2024-01-31 15:07 UTC, mohamedkallel approved these changes

2024-02-01 16:09 UTC, GeorgiTsatsev approved these changes

2024-02-01 16:09 UTC, merged