CD-323: HPE MSA SAN - Overall Unit Status - REST API
domotz/custom-driver pull request #224
Opened 2024-02-07 09:42 UTC by mariemm97

2024-02-13 13:02 UTC, mohamedkallel requested changes

2024-02-13 13:02 UTC, mohamedkallel commented on examples/http/hpe_msa_san_overall_unit_status.js
> +function extractData(data) {
use the xml library instead of manual parsing

2024-02-15 11:58 UTC, mohamedkallel approved these changes

2024-02-20 07:44 UTC, GeorgiTsatsev approved these changes

2024-02-20 07:44 UTC, merged