CD-325: HPE MSA SAN - HW Sensors - Voltage/Current - REST API
domotz/custom-driver pull request #226
Opened 2024-02-09 09:24 UTC by mariemm97

2024-02-13 13:10 UTC, mohamedkallel requested changes

2024-02-13 13:10 UTC, mohamedkallel commented on examples/http/hpe_msa_san_hardware_sensors_voltage_current.js
> +function extractData(data) {
use the xml library instead of manual parsing
D.htmlParse(xml)
refer to some examples done before like aws_ec2_volumes.js

2024-02-15 12:03 UTC, mohamedkallel approved these changes

2024-02-20 10:06 UTC, GeorgiTsatsev commented on examples/http/hpe_msa_san_hardware_sensors_voltage_current.js
> +        { label: "Value", unit: "V", valueType: D.valueType.NUMBER},
The Value unit is not correct for Current. I suggest an extra column for current if grouping is possible

2024-02-22 11:29 UTC, mohamedkallel approved these changes

2024-03-05 10:37 UTC, mohamedkallel approved these changes

2024-03-05 10:37 UTC, mohamedkallel requested changes

2024-03-06 12:01 UTC, mohamedkallel approved these changes

2024-03-07 09:39 UTC, GeorgiTsatsev approved these changes

2024-03-07 09:39 UTC, merged