CD-353: VMWare vCenter Monitoring - System Health
domotz/custom-driver pull request #255
Opened 2024-02-27 11:09 UTC by mariemm97

2024-03-05 10:49 UTC, mohamedkallel requested changes

2024-03-05 10:49 UTC, mohamedkallel commented on examples/http/vmware_vcenter_monitoring_system_health.js
> +function getHealthSystemsUrls(url) {
there is no need for this function, you can use directly httpGet(url, sessionId)

2024-03-05 10:49 UTC, mohamedkallel commented on examples/http/vmware_vcenter_monitoring_system_health.js
> +    var recordIds = [
make this as a global configuration variable
config = {id: "system-health", url: "/api/appliance/health/system" ...}
in getSystemHealthInfo build a list of promises based on this config then in extract data make the same code based on the iteration on the id of the configuration

2024-03-06 11:50 UTC, mohamedkallel approved these changes

2024-03-07 12:03 UTC, GeorgiTsatsev commented on examples/http/vmware_vcenter_monitoring_system_health.js
> +    { id: "system-health", url: "/api/appliance/health/system" }, //Get overall health of system
the table name is "System Health" 
having -health is redundant

2024-03-07 12:03 UTC, GeorgiTsatsev commented on examples/http/vmware_vcenter_monitoring_system_health.js
> +    { id: "memory-health", url: "/api/appliance/health/mem" }, //Get memory health
having -health is redundant

2024-03-07 12:03 UTC, GeorgiTsatsev commented on examples/http/vmware_vcenter_monitoring_system_health.js
> +    { id: "applmgmt-service-health", url: "/api/appliance/health/applmgmt" }, //Get health status of applmgmt services
having -health is redundant

2024-03-08 08:52 UTC, GeorgiTsatsev approved these changes

2024-03-08 08:53 UTC, merged