CD-412
domotz/custom-driver pull request #318
Opened 2024-08-06 12:05 UTC by PivaFiras

- Add ESXi General Information script
- Add script description JSON

2024-08-08 07:50 UTC, mohamedkallel requested changes

2024-08-08 07:50 UTC, mohamedkallel commented on examples/http/esxi_general_information.js
> +  const variables = [
put this as global variable and use it to generate the retreive properties envelope

2024-08-08 07:50 UTC, mohamedkallel commented on examples/http/esxi_general_information.js
> +function setHeaders(headerCookie) {
why do not use jar: true parameter instead of setting the headers manually

2024-08-08 14:28 UTC, mohamedkallel requested changes

2024-08-08 14:28 UTC, mohamedkallel commented on examples/http/esxi_general_information.js
> +      '         <vim25:pathSet>runtime.connectionState</vim25:pathSet>' +
please use the defined global variable "variables" that you created

2024-08-16 07:56 UTC, GeorgiTsatsev commented on examples/http/esxi_general_information.js
> +function login () {
what if the login is unsuccessful ? There is no proper handling of that (it must call the D.failure callback with the relevant error - D.errorType.AUTHENTICATION_ERROR )

2024-08-16 07:58 UTC, GeorgiTsatsev approved these changes

2024-08-16 07:58 UTC, merged