Cd 8
domotz/custom-driver pull request #35
Opened 2023-01-23 08:16 UTC by mariemm97

Add new driver RabbitMQ nodes. 
Add comments.

2023-02-01 06:43 UTC, mohamedkallel requested changes
the code is good, just fix the comments I added

2023-02-01 06:43 UTC, mohamedkallel commented on sandbox_emulator/.env copy
> +DEVICE_IP=18.102.29.37
this file should not be commited, it's name should be .env.sample.{device_name} to be ignored

2023-02-01 06:43 UTC, mohamedkallel commented on examples/http/rabbitmq_cluster.js
> +    monitoringList = [
add comment for each monitoring variable

2023-02-01 06:43 UTC, mohamedkallel commented on examples/http/rabbitmq_cluster.js
> +function fillTable() {
add comment what the table will contain

2023-02-01 06:43 UTC, mohamedkallel commented on examples/http/rabbitmq_cluster.js
> +//Load all data
explain more which data will be loaded

2023-02-01 06:43 UTC, mohamedkallel commented on examples/http/rabbitmq_nodes.js
> + * The rabbitmq cluster name is modified in each installation.So, you can find it in the right side of the rabbitmq GUI. example: Cluster rabbit@319ac541e311
Correct it by:
The rabbitmq cluster name is modified in each installation. it should be found in in the top right corner of the RabbitMQ web application after making the signin. example: Cluster rabbit@319ac541e311

2023-02-01 06:43 UTC, mohamedkallel commented on examples/http/rabbitmq_nodes.js
> +// load all data
explain more which what data is loaded

2023-02-01 06:43 UTC, mohamedkallel commented on examples/http/rabbitmq_nodes.js
> +        {
add a description for each variable

2023-02-10 07:04 UTC, GeorgiTsatsev approved these changes

2023-02-10 07:05 UTC, GeorgiTsatsev approved these changes

2023-02-10 07:30 UTC, GeorgiTsatsev approved these changes

2023-02-10 07:32 UTC, mohamedkallel approved these changes

2023-02-10 07:33 UTC, merged