CD-539
domotz/custom-driver pull request #386
Opened 2024-11-04 16:31 UTC by PivaFiras

- Add Azure - Containers script
- Add script description JSON

2024-11-17 17:06 UTC, mohamedkallel requested changes

2024-11-17 17:06 UTC, mohamedkallel commented on examples/http/azure_containers.js
> +            containerGroupInfoList = filterContainerGroupInfoListByResourceGroups(filterContainerGroupInfoListByContainerNames(filterContainerGroupHadContainers(containerGroupInfoList)));
why we should iterate over and over and over 3 times, we can iterate with only one filter and make our 3 conditions

2024-11-17 17:06 UTC, mohamedkallel commented on examples/http/azure_containers.js
> +    const d = D.q.defer();
why we are using promise for a simple insert to a table?

2024-11-17 17:06 UTC, mohamedkallel commented on examples/http/azure_containers.js
> +    const promises = containerGroupInfoList.map(function (containerGroupInfo) {
please for promises use D.q and do not use Promise

create a promies variable as empty array and iterate over containerGroupInfoList and then iterate over performanceKeyGroups and in the second loop create a defer and push d.promise to your promises table

2024-11-17 17:06 UTC, mohamedkallel commented on examples/http/azure_containers.js
> +    return D.q.all(promises);
why using promises for simple insert record to the table

2024-11-21 10:36 UTC, mohamedkallel approved these changes

2024-11-21 10:44 UTC, mohamedkallel approved these changes

2024-11-25 07:36 UTC, GeorgiTsatsev approved these changes

2024-11-25 07:36 UTC, merged