Add driver iperf
domotz/custom-driver pull request #56
Opened 2023-03-24 09:27 UTC by mariemm97

2023-04-19 08:51 UTC, mohamedkallel requested changes

2023-04-19 08:51 UTC, mohamedkallel commented on examples/ssh/iperf.js
> + * UDPup: test for UDP upload speed.
add the iperf version tested with and the operating system used

2023-04-24 17:31 UTC, mohamedkallel approved these changes

2023-04-28 12:35 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +var dload, uload, udpdload, udpuload;  // Define variables for storing download/upload speeds
use more descriptive names
var downloadSpeed, uploadSpeed, uploadSpeedUDP, downloadSpeedUDP

2023-04-28 12:35 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +var _var = D.device.createVariable;
use D.createVariable directly and avoid defining this

2023-04-28 12:37 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +var UDP = "Y"; // Define whether UDP is enabled on the device (set to "Y" by default)
What is this variable for?  And if its conditional why not set it a boolean? 
If its a flag to test UDP or not name it properly

eg 'shouldTestUDPSpeed'

2023-04-28 12:37 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +    var config = JSON.parse(JSON.stringify(sshConfig));
Why do you stringify and then parse?

2023-04-28 12:37 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +function exec_command(command, callback) {
use camelCase

2023-04-28 12:38 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +    exec_command(commands[0], function (cmd) {
Just use promises to execute all of the commands 

the callback structure is a bit strange for cascading 4 calls

2023-04-28 12:44 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +                            _var("down", "DLOAD", dload, "Mb/s"),
use better naming and uids

download-speed
upload-speed
download-speed-udp
download-speed-UDP

2023-04-28 12:44 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +                            _var("up", "ULOAD", uload, "Mb/s"),
The Labels should be clear as well

"Upload Speed" etc

2023-04-28 12:46 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +            .catch(failure);
the catch must be for the execution function not the D.success

2023-04-28 12:46 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +            .catch(failure);
the catch must be for the execute function

2023-04-28 12:47 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +function validate() {
This validate function does not capture erroneous cases

Eg validate on any device with a working SSH will result in an OK and it MUST NOT

Please add a proper validation if the device has iperf3 installed and can run the respective commands

2023-04-28 12:48 UTC, GeorgiTsatsev commented on examples/ssh/iperf.js
> +            }
What about a failure in parsing (eg no output)???

2023-05-03 11:41 UTC, mohamedkallel approved these changes

2023-05-15 13:39 UTC, GeorgiTsatsev approved these changes

2023-05-15 13:39 UTC, merged